# Generated by Django 4.0.5 on 2022-06-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='same_shipping_address',
            field=models.BooleanField(default=True, verbose_name="L'adresse d'expédition est identique à l'adresse de facturation"),
        ),
    ]
