# Generated by Django 4.0.5 on 2022-06-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_billingaddress_same_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='email',
            field=models.CharField(default='a@a.com', max_length=50, verbose_name='Adresse Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='phone',
            field=models.CharField(default='1234567', max_length=50, verbose_name='Numéro de téléphone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='company_name',
            field=models.CharField(blank=True, help_text='Optionnel', max_length=100, null=True, verbose_name='Société (optionnel)'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='street_address_line_2',
            field=models.CharField(blank=True, help_text='Optionnel', max_length=100, null=True, verbose_name="Complément d'adresse"),
        ),
    ]
