# Generated by Django 4.0.5 on 2022-06-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customer_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user_id',
        ),
    ]
