# Generated by Django 4.0.5 on 2022-06-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_address_options_customer_anonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='same_shipping_address',
            field=models.BooleanField(default=True),
        ),
    ]
