# Generated by Django 4.0.5 on 2022-06-27 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_same_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='same_shipping_address',
            new_name='same_billing_address',
        ),
    ]
