# Generated by Django 4.0.5 on 2022-07-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_mondialrelayinfo_alter_order_delivery_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('H', 'Livraison à Domicile'), ('R', 'Livraison en Point Relay')], max_length=1, verbose_name='Options de livraison'),
        ),
    ]
