# Generated by Django 4.0.5 on 2022-07-09 16:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_delivery_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=django_countries.fields.CountryField(default='fr', max_length=2, verbose_name='Pays de livraison'),
        ),
    ]
