# Generated by Django 4.0.5 on 2022-07-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_shipping_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mondial_relay_info',
        ),
        migrations.AddField(
            model_name='order',
            name='mondial_relay_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('B', 'Facturation'), ('S', 'Expédition'), ('R', 'Point relais')], max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('H', 'Livraison à Domicile'), ('R', 'Livraison en Point Relay'), ('I', 'Livraison international')], max_length=1, verbose_name='Options de livraison'),
        ),
        migrations.DeleteModel(
            name='MondialRelayInfo',
        ),
    ]
