# Generated by Django 4.0.5 on 2022-06-26 20:34

import beekeeping_ecommerce.contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demorequest',
            name='accept_conditions',
            field=models.BooleanField(validators=[beekeeping_ecommerce.contact.models.validate_confidentiality], verbose_name='Accepter la politique de confidentialité'),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse Email'),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nom de Famille'),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='post_code',
            field=models.CharField(max_length=10, verbose_name='Code Postal'),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='requested_date',
            field=models.DateField(help_text='au format jj/mm/aaaa', validators=[beekeeping_ecommerce.contact.models.validate_date_requested], verbose_name='Date souhaitée'),
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='shop_name',
            field=models.CharField(max_length=255, verbose_name='Nom du Magasin'),
        ),
    ]
