# Generated by Django 4.0.5 on 2022-06-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_demorequest_accept_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demorequest',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Numéro de téléphone'),
        ),
    ]
